// <auto-generated />
using DisneyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DisneyApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521183804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CharacterMedia", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("character_id");

                    b.Property<int>("MediId")
                        .HasColumnType("integer")
                        .HasColumnName("medi_id");

                    b.Property<string>("MediaType")
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.HasKey("CharacterId", "MediId", "MediaType")
                        .HasName("pk_character_media");

                    b.HasIndex("MediId", "MediaType")
                        .HasDatabaseName("ix_character_media_medi_id_media_type");

                    b.ToTable("character_media", (string)null);
                });

            modelBuilder.Entity("DisneyApi.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Films")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("films");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortFilms")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_films");

                    b.Property<string>("TvShows")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tv_shows");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("DisneyApi.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("MediaType")
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<string>("PosterPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("poster_path");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("release_date");

                    b.Property<float>("VoteAvg")
                        .HasColumnType("real")
                        .HasColumnName("vote_avg");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer")
                        .HasColumnName("vote_count");

                    b.HasKey("Id", "MediaType")
                        .HasName("pk_medias");

                    b.ToTable("medias", (string)null);
                });

            modelBuilder.Entity("CharacterMedia", b =>
                {
                    b.HasOne("DisneyApi.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_media_characters_character_id");

                    b.HasOne("DisneyApi.Models.Media", null)
                        .WithMany()
                        .HasForeignKey("MediId", "MediaType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_media_medias_medi_id_media_type");
                });
#pragma warning restore 612, 618
        }
    }
}
